gautamkrishnar/nothing-private

index.html

Issue : Github star button showing a warning - fixed

---

index.html

* Added a doctype and language attribute. Not essential but nice to have.
* Fixed typo in title.
* Small phrasing change to description.

A couple of small tweaks and typo fix

---

README.md

I'm just knowing this project, very nice! When I was reading the README the first thing I did was to look for a link to Client.js, given that I didn't know it.
That's why I created this PR so other people visiting the project can quickly browse the technologies used.

Add links for technologies

---

index.html

added new icon for facebook share

---

db_server/forgetme.php
db_server/safedb.php
main.js

- Added a button to remove your data from database;
- Fixed some warnings in javascript file;

added forget me button

---

README.md

Added few commas to readme file.

Added few commas to readme file

---

README.md

updated contributors list

---

README.md
index.html
main.js
style.css

* made minor changes to the design of the site to unify the typographic identity
* improved the user-facing text defined in `main.js` and `index.html`
* proofread and edited `README.md`
Currently, the site looks like the following:
This pull request changes the typographic identity of the site to a more consistent sans-serif font (`Arial` by default, with fallback to `Helvetica` and `sans-serif`):
This involved minor changes to `index.html` as well as `style.css`. (See 59668a8.)
There were a few minor issues with the text on the site. I've gone through and edited the text to make it read smoothly in standard American/British English. (See 85e9076.)
I proofread `README.md` and made a few small changes to improve the readability, consistency, and accuracy of the text. (I also added myself …

Minor design change and text improvements

---

index.html

Title: Update index.html
caps looks nice for any title :)
Copy of #39 to test continuous intgration

Title case changed

---

README.md

This pull request does the following:
* Update some links to HTTPS
* Use original version of meme image
* Capitalize `Focus` in Firefox Focus.

Update a handful of links to HTTPS and other README updates

---

package-lock.json
style.css

https://github.com/gautamkrishnar/nothing-private/issues/55
Was tested via Browserstack on different mobile devices
Before:
After:

add height for correctly displaying on real mobile devices

---

README.md

Added an Extra Reference -
https://spreadprivacy.com/browser-fingerprinting/

Update README.md with extra reference

---

Secure-Browsers.md

I fixed a typo in the file "Secure-browsers.md"
https://github.com/gautamkrishnar/nothing-private/issues/38
In the README.md, it says: "To do: Fix any typos"
This has not been tested, as it is only a change in a text file.

Fix typo in Secure-Browsers.md

---

README.md
firefox_quantum_notes.md
pale_moon_notes.md
waterfox_notes.md

Fixed minor typos in four files
Added commas and fixed typos
Contributing to the task of - To do: Fix any typos
n/a

Fix typos in readme and notes

---

index.html
style.css

Minor Stylesheet changes and Typos fix
1. Fixed star on Gihub to start on Github.
2. Increased padding between social media buttons.
3. Highlighted the name in the copyright section.
4. Increased readability for Html and Css files.
1. The concept is great, the page looks more awesome now.
1. I have locally run the project and it is working fine.

Word Fix and minor style sheet changes

---

main.js

fix button mulitple time clicked reloads page bug
Clicking 'See the magic!' button multiple times reloads the page more than once
Verified the change on chrome, edge, ie, firefox

fix button mulitple time clicked reloads page bug

---

README.md

Add `contributing guidelines` reference.
N/A
The user may miss out the contributing guidelines if not mentioned as part of the docs.
N/A
N/A

[Docs]: Add contributing guidelines info

---

browsers-with-countermeasures/README.md

Implement @Thorin-Oakenpants proposals for better wording in https://github.com/gautamkrishnar/nothing-private/pull/107.

Improve explanations and add new firefox version to the list.

---

browsers-with-countermeasures/README.md

added the brave browser to the list, tested on linux and windows

added brave to browsers-with-countermeasures.md

---

main.js

using dot after exclamation mark is a typo

Fix dot after exclamation mark typo

---

browsers-with-countermeasures/README.md

Add Android devices to the list since Brave for android implements countermeasures
I tried it on my own device

Add Android to the systems list where Brave works
